### PR TITLE
Fixes version installation problems and refactors module

### PR DESCRIPTION
**Pull request by colin-nolan**
I initially thought a fix for #17 would be simple but soon found that there is much more subtlety to the way Conda deals with package versions! Hopefully I've addressed all of the edge cases here.

This fix has turned into a rather large refactoring of the module, which also addresses a fair few problems that weren't previously reported. I've added more testing and hopefully made the code easier to work with in the future.

Sorry for making so many changes in one go!

### CODE REVIEW

**Comment by jiffyclub** [comment]
Thanks! I will try to review this as soon as I can.

**Comment by danielballan** [comment]
I'm interested in building on this to support awareness of environments other than the root environment. Please let me know if I can do anything to help shepherd this along, @jiffyclub. :- )

**Comment by colin-nolan** [comment]
@jiffyclub did you manage to get a chance to review this?

**Comment by jiffyclub** [comment]
It looks fine to me, but I don't use this anymore so I'm going to take your word that it works! @colin-nolan, would you be potentially interested in taking over maintenance of this?

**Comment by jiffyclub** [comment]
@colin-nolan FYI the Travis run failed post-merge: https://travis-ci.org/UDST/ansible-conda/builds/335736685

**Pull request merged**
